apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: temple-stack
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/hcmuleva/els-professional-kits.git
    targetRevision: HEAD
    path: dev-test-ops-pro/level5/devops/temple-stack
    helm:
      valueFiles:
        - values.yaml
        - values-dev.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: temple-stack
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
