apiVersion: v1
kind: Service
metadata:
  name: react-ui
spec:
  selector: { app.kubernetes.io/name: react-ui }
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.containerPort }}
