apiVersion: v2
name: pact-stack
description: Umbrella chart for postgres and fabric-pact-broker
type: application
version: 1.0.0
appVersion: "1.0"

dependencies:
  - name: postgres
    version: 1.0.0
    repository: "file://./fabric-postgres"
    condition: postgres.enabled
    tags:
      - database
  - name: fabric-pact-broker
    version: 1.0.0
    repository: "file://./fabric-pact-broker"
    condition: fabric-pact-broker.enabled
    tags:
      - broker