apiVersion: v1
data:
  POSTGRES_DB: cGFjdGJyb2tlcg==
  POSTGRES_PASSWORD: WU9VUl9TRUNVUkVfUEFTU1dPUkQ=
  POSTGRES_USER: cG9zdGdyZXM=
kind: Secret
metadata:
  creationTimestamp: null
  name: pact-stack-db-auth
  namespace: pact-stack
