apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  clusterIP: None
  selector: { app.kubernetes.io/name: postgres }
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
