replicaCount: 1

image:
  repository: social-network
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
  hosts:
    - host: yourdomain.com
      paths:
        - path: /ui/?(.*)
          pathType: Prefix
  tls: []
