# ===========================================
# Common configuration
# ===========================================
replicaCount: 1
imagePullPolicy: Never

# ===========================================
# React App configuration
# ===========================================
templeui:
  name: temple-ui
  image: temple-ui
  tag: "1.1"
  containerPort: 80
  servicePort: 80
  env:
    REACT_APP_ABLY_API_KEY: xul13A.CNpeww:KkS0rh8M4rJSr5r4gHNGbMijYuxvr90ybz1UQd6uKpw
    REACT_APP_MAXPAGE: 3
    REACT_APP_KRUTRIM_API_KEY: 5MG974Dkz5xHQ70hLzyLZQzMO57B5P9Pos1MOYe3
    REACT_APP_GOOGLE_API_KEY: AIzaSyDNN9LVrNB_WOGhrHG0U1CYsTWIOuaaoI8
    REACT_APP_PINCODE: https://emeelan.com/alumniserver/api
    REACT_APP_API_URL: http://temple-api.local//api   

# ===========================================
# Ingress configuration
# ===========================================
ingress:
  enabled: true
  name: temple-ui-ingress
  className: nginx
  # Add the following annotations section
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  paths:
    - path: /
      pathType: Prefix
      service: temple-ui-service
      port: 80

  