apiVersion: v1
kind: Service
metadata:
  name: {{ include "fabric-postgres.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "fabric-postgres.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  clusterIP: None 
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: postgres
  selector:
    {{- include "fabric-postgres.labels" . | nindent 4 }}