{{- if and .Values.basicAuth.enabled (not .Values.basicAuth.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "fabric-pact-broker.fullname" . }}-auth
  labels:
    {{- include "fabric-pact-broker.labels" . | nindent 4 }}
type: Opaque
stringData:
  username: {{ .Values.basicAuth.username | quote }}
  password: {{ .Values.basicAuth.password | quote }}
  {{- if .Values.basicAuth.readOnlyUsername }}
  readonly-username: {{ .Values.basicAuth.readOnlyUsername | quote }}
  {{- end }}
 
{{- end }}