apiVersion: v1
kind: Secret
metadata:
  name: {{ include "fabric-pact-broker.secretName" . }}
  labels:
    {{- include "fabric-pact-broker.labels" . | nindent 4 }}
type: Opaque
data:
  POSTGRES_DB: {{ .Values.database.name | b64enc }}
  POSTGRES_USER: {{ .Values.database.username | b64enc }}
  POSTGRES_PASSWORD: {{ .Values.database.password | b64enc }}
