apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "my-react-app.fullname" . }}
  labels:
    app: {{ include "my-react-app.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "my-react-app.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "my-react-app.name" . }}
    spec:
      containers:
        - name: react-app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
