# ---- Global / convenience ----
nameOverride: ""
fullnameOverride: ""

# Your local IP (used to auto-create a working hostname with sslip.io)
# Example: if your Mac LAN IP is 192.168.1.50 → host becomes pact.192.168.1.50.sslip.io
localIP: "127.0.0.1"
hostPrefix: "pact"

ingress:
  enabled: true
  className: "nginx"
  annotations: {}
  # path: "/" # default
  tls:
    enabled: false
    secretName: "" # only if you enable tls

# ---- Postgres settings ----
postgres:
  image: "postgres:15"
  imagePullPolicy: IfNotPresent
  storage:
    size: 5Gi
    storageClassName: ""  # empty uses default (Docker Desktop supports default)
  service:
    port: 5432
  auth:
    database: "pactbroker"
    username: "pactuser"
    # Put a dev password here or override via --set/values file
    password: "pactpass"
  # Kubernetes resources
  resources: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}
brokerAuth:
  username: admin
  password: strongpassword123

broker:
  image: "pactfoundation/pact-broker:latest"
  imagePullPolicy: IfNotPresent
  replicas: 1
  service:
    port: 9292
  env:
    ENABLE_BASIC_AUTH: "true"   # toggle here
    PACT_BROKER_AUTO_MIGRATE: "true"
    PACT_BROKER_LOG_LEVEL: "info"
  resources: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}
