version: '3.8'

services:
  allure:
    image: frankescobar/allure-docker-service:latest
    container_name: allure-report-server
    ports:
      - "5050:5050"  # Allure UI
      - "5051:5252"  # Allure API (changed from 5252 to 5051)
    environment:
      CHECK_RESULTS_EVERY_SECONDS: 3
      KEEP_HISTORY: 1
      KEEP_HISTORY_LATEST: 25
    volumes:
      - ./allure-results:/app/allure-results
      - ./allure-reports:/app/default-reports
    networks:
      - allure-network
    restart: unless-stopped

  allure-ui:
    image: frankescobar/allure-docker-service-ui:latest
    container_name: allure-ui
    ports:
      - "5253:5252"  # UI port (changed from 5252 to 5253)
    environment:
      ALLURE_DOCKER_PUBLIC_API_URL: "http://localhost:5050"
      ALLURE_DOCKER_PUBLIC_API_URL_PREFIX: ""
    networks:
      - allure-network
    depends_on:
      - allure
    restart: unless-stopped

networks:
  allure-network:
    driver: bridge