{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "pact-broker-stack.broker.fullname" . }}
  labels:
    {{- include "pact-broker-stack.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  {{- if .Values.ingress.tls.enabled }}
  tls:
    - hosts:
        - {{ printf "%s.%s.sslip.io" .Values.hostPrefix .Values.localIP | quote }}
      secretName: {{ .Values.ingress.tls.secretName }}
  {{- end }}
  rules:
    - host: {{ printf "%s.%s.sslip.io" .Values.hostPrefix .Values.localIP | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "pact-broker-stack.broker.fullname" . }}
                port:
                  number: {{ .Values.broker.service.port }}
{{- end }}
