apiVersion: v1
kind: Service
metadata:
  name: {{ include "pact-broker-stack.postgres.fullname" . }}
  labels:
    {{- include "pact-broker-stack.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.postgres.service.port }}
      targetPort: 5432
      name: postgres
  selector:
    app: {{ include "pact-broker-stack.postgres.fullname" . }}
